language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update
  - dpkg --get-selections | grep hold
  - sudo apt-get install -qq ia32-libs ia32-libs-multiarch
  - sudo apt-get install ncurses-dev

script: make
